### ISSUE TITLE
Theme switches on each update

### ISSUE THREAD

**Issue by jk779** [dracula/jetbrains#60] opened 2021-09-01 11:37 UTC
Hi!

I'm having a issue similiar to https://github.com/dracula/jetbrains/issues/29.

While updating this plugin, Webstorm, Rubymine and Goland open a small popup progress bar reading "Unloading Plugin", after that the IDE switches to the default-ish dracula theme:
<img width="369" alt="Bildschirmfoto 2021-09-01 um 13 33 01" src="https://user-images.githubusercontent.com/1104528/131664459-acc1dc42-5787-4c01-a870-7422d901a3ab.png">

When closing the preferences window, it wants me to restart, but after the restart this theme is still selected.

I'm using Dracula Colorful, which I have to select again after each update. Am I missing something?

Used Theme:
<img width="369" alt="Bildschirmfoto 2021-09-01 um 13 33 28" src="https://user-images.githubusercontent.com/1104528/131664655-0309192d-c26d-43bc-9fe2-2d90098ba37a.png">

**Comment by WhiteVermouth** [comment] 2021-09-05 06:03
This bug is introduced by JetBrains IDE itself. The IDE is expected to automatically unload and then load back the theme plugin during plugin updating. But sometimes it just fails to load back the plugin, and therefore the user has to switch back theme manually. We can do nothing but wait for JetBrains's bug fix. Sorry.

**Comment by ramsaysewell** [comment] 2024-04-03 22:55
Closing this issue due to the bug no longer being reproducible in JetBrains IDEs. Feel free to leave a comment if you're still having issues however as stated, we're out of control of IDE-based bugs.

**Closed as completed** 2024-04-03 22:55 UTC
